var slidesData=[
    {
        marque:"GuCHUUUUUUU",
        description:"mech normal mansouh bih 3alekher seeeehbii",
        image:"img1.png"
    },
    {
        marque:"cristioanioooo",
        description:"SUUUUUUUUU",
        image:"img2.png"
    },
    {
        marque:"Gucci",
        description:"good XD",
        image:"img1.png"
    },
    {
        marque:"cristioanioooo",
        description:"SUUUUUUUUU",
        image:"img2.png"
    },
    {
        marque:"cristioanioooo",
        description:"SUUUUUUUUU",
        image:"img1.png"
    }
]

var favoriteData=[
    {
        marque:"GuCHUUUUUUU",
        description:"mech normal mansouh bih 3alekher seeeehbii",
        image:"img1.png",
    }
]

module.exports= {slidesData,favoriteData}